[package]
name = "pocket-island-3ds"
version = "0.1.0"
edition = "2024"
license = "MIT"
[lib]
crate-type = ["staticlib"]
[workspace]
[dependencies]
pocket-island = { path = "../.." }
pocket3d-mesh = { path = "../../vendor/pocketjs/engine/pocket3d/crates/pocket3d-mesh" }
[profile.release]
opt-level = 3
lto = true
panic = "abort"
codegen-units = 1
